### ISSUE TITLE
Error running run.py in a virtualenv

### ISSUE THREAD

**Issue by mertenats** [akamai-threat-research/mqtt-pwn#1]
I've a problem running `run.py`

Used commands :
```
virtualenv -p /usr/bin/python3 mqtt-pwn
cd mqtt-pwn/
source bin/activate
git clone https://github.com/akamai-threat-research/mqtt-pwn.git
pip3 isntall -r mqtt-pwn/requirements.txt 
python3 mqtt-pwn/run.py
```

Error :
```
(mqtt-pwn) samuel@computername:~/Softwares/mqtt-pwn$ python3 mqtt-pwn/run.py Traceback (most recent call last):
  File "/home/samuel/Softwares/mqtt-pwn/lib/python3.6/site-packages/peewee.py", line 2514, in connect
    self._state.set_connection(self._connect())
  File "/home/samuel/Softwares/mqtt-pwn/lib/python3.6/site-packages/peewee.py", line 3068, in _connect
    conn = psycopg2.connect(database=self.database, **self.connect_params)
  File "/home/samuel/Softwares/mqtt-pwn/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "db" to address: Name or service not known


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/samuel/Softwares/mqtt-pwn/lib/python3.6/site-packages/peewee.py", line 2565, in execute_sql
    cursor = self.cursor(commit)
  File "/home/samuel/Softwares/mqtt-pwn/lib/python3.6/site-packages/peewee.py", line 2551, in cursor
    self.connect()
  File "/home/samuel/Softwares/mqtt-pwn/lib/python3.6/site-packages/peewee.py", line 2515, in connect
    self._initialize_connection(self._state.conn)
  File "/home/samuel/Softwares/mqtt-pwn/lib/python3.6/site-packages/peewee.py", line 2367, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/home/samuel/Softwares/mqtt-pwn/lib/python3.6/site-packages/peewee.py", line 175, in reraise
    raise value.with_traceback(tb)
  File "/home/samuel/Softwares/mqtt-pwn/lib/python3.6/site-packages/peewee.py", line 2514, in connect
    self._state.set_connection(self._connect())
  File "/home/samuel/Softwares/mqtt-pwn/lib/python3.6/site-packages/peewee.py", line 3068, in _connect
    conn = psycopg2.connect(database=self.database, **self.connect_params)
  File "/home/samuel/Softwares/mqtt-pwn/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
peewee.OperationalError: could not translate host name "db" to address: Name or service not known


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mqtt-pwn/run.py", line 9, in <module>
    create_all_tables(db)
  File "/home/samuel/Softwares/mqtt-pwn/mqtt-pwn/mqtt_pwn/database.py", line 49, in create_all_tables
    create_tables(db, _all_tables)
  File "/home/samuel/Softwares/mqtt-pwn/mqtt-pwn/mqtt_pwn/database.py", line 41, in create_tables
    db.create_tables(tables)
  File "/home/samuel/Softwares/mqtt-pwn/lib/python3.6/site-packages/peewee.py", line 2715, in create_tables
    model.create_table(**options)
  File "/home/samuel/Softwares/mqtt-pwn/lib/python3.6/site-packages/peewee.py", line 5445, in create_table
    and cls.table_exists():
  File "/home/samuel/Softwares/mqtt-pwn/lib/python3.6/site-packages/peewee.py", line 5435, in table_exists
    return meta.database.table_exists(meta.table, meta.schema)
  File "/home/samuel/Softwares/mqtt-pwn/lib/python3.6/site-packages/peewee.py", line 2693, in table_exists
    return table.__name__ in self.get_tables(schema=schema)
  File "/home/samuel/Softwares/mqtt-pwn/lib/python3.6/site-packages/peewee.py", line 3092, in get_tables
    cursor = self.execute_sql(query, (schema or 'public',))
  File "/home/samuel/Softwares/mqtt-pwn/lib/python3.6/site-packages/peewee.py", line 2574, in execute_sql
    self.commit()
  File "/home/samuel/Softwares/mqtt-pwn/lib/python3.6/site-packages/peewee.py", line 2367, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/home/samuel/Softwares/mqtt-pwn/lib/python3.6/site-packages/peewee.py", line 175, in reraise
    raise value.with_traceback(tb)
  File "/home/samuel/Softwares/mqtt-pwn/lib/python3.6/site-packages/peewee.py", line 2565, in execute_sql
    cursor = self.cursor(commit)
  File "/home/samuel/Softwares/mqtt-pwn/lib/python3.6/site-packages/peewee.py", line 2551, in cursor
    self.connect()
  File "/home/samuel/Softwares/mqtt-pwn/lib/python3.6/site-packages/peewee.py", line 2515, in connect
    self._initialize_connection(self._state.conn)
  File "/home/samuel/Softwares/mqtt-pwn/lib/python3.6/site-packages/peewee.py", line 2367, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/home/samuel/Softwares/mqtt-pwn/lib/python3.6/site-packages/peewee.py", line 175, in reraise
    raise value.with_traceback(tb)
  File "/home/samuel/Softwares/mqtt-pwn/lib/python3.6/site-packages/peewee.py", line 2514, in connect
    self._state.set_connection(self._connect())
  File "/home/samuel/Softwares/mqtt-pwn/lib/python3.6/site-packages/peewee.py", line 3068, in _connect
    conn = psycopg2.connect(database=self.database, **self.connect_params)
  File "/home/samuel/Softwares/mqtt-pwn/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
peewee.OperationalError: could not translate host name "db" to address: Name or service not known
```

Postgres :
```
samuel@computername:~/Softwares/mqtt-pwn$ sudo -u postgres psql postgres
[sudo] password for samuel: 
could not change directory to "/home/samuel/Softwares/mqtt-pwn": Permission denied
psql (9.6.9)
Type "help" for help.

postgres=# 
```

Thanks

**Comment by Den1al** [comment]
Hi, thanks for your input.
In the `config.py` file there is a variable called `DB_HOST` which is by default initiated to `db` (which is the value that the docker-compose daemon assigns to the postgres instance.

Simply change it to the host your postgres instance is running (i.e. `127.0.0.1`). Let me know if you're facing more issues.

**Comment by mertenats** [comment]
Thanks! It's now working fine.

**Comment by diegocatalanc** [comment]
y en el caso con MySQL?
