### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by shaolinint** [akamai-threat-research/mqtt-pwn#6]
OS: Ubuntu 19.04
Python version: 3.7.3

>> connect
[!] Connecting...
Traceback (most recent call last):
  File "/home/sneakyrat/.local/lib/python3.7/site-packages/cmd2/cmd2.py", line 1716, in onecmd_plus_hooks
    stop = self.onecmd(statement)
  File "/home/sneakyrat/.local/lib/python3.7/site-packages/cmd2/cmd2.py", line 1951, in onecmd
    stop = func(statement)
  File "/home/sneakyrat/.local/lib/python3.7/site-packages/cmd2/cmd2.py", line 241, in cmd_wrapper
    return func(instance, args)
  File "/home/sneakyrat/pentest/iot/mqttpwn/mqtt_pwn/shell/mixins/connect.py", line 40, in do_connect
    self._connect(args)
  File "/home/sneakyrat/pentest/iot/mqttpwn/mqtt_pwn/shell/mixins/connect.py", line 82, in _connect
    self.mqtt_client.run()
AttributeError: 'NoneType' object has no attribute 'run'
EXCEPTION of type 'AttributeError' occurred with message: ''NoneType' object has no attribute 'run''

**Comment by AmarPatel12** [comment]
Just want to add to this as I'm experiencing the same issue. 

OS: MacOS 10.13.6
Python Version: 3.8.1


>> connect
[!] Connecting...
Traceback (most recent call last):
  File "/Users/amarpatel/.pyenv/versions/3.8.1/lib/python3.8/site-packages/cmd2/cmd2.py", line 1716, in onecmd_plus_hooks
    stop = self.onecmd(statement)
  File "/Users/amarpatel/.pyenv/versions/3.8.1/lib/python3.8/site-packages/cmd2/cmd2.py", line 1951, in onecmd
    stop = func(statement)
  File "/Users/amarpatel/.pyenv/versions/3.8.1/lib/python3.8/site-packages/cmd2/cmd2.py", line 241, in cmd_wrapper
    return func(instance, args)
  File "/Users/amarpatel/IOT/mqtt-pwn/mqtt_pwn/shell/mixins/connect.py", line 40, in do_connect
    self._connect(args)
  File "/Users/amarpatel/IOT/mqtt-pwn/mqtt_pwn/shell/mixins/connect.py", line 82, in _connect
    self.mqtt_client.run()
AttributeError: 'NoneType' object has no attribute 'run'
EXCEPTION of type 'AttributeError' occurred with message: ''NoneType' object has no attribute 'run''

Is anyone able to shed some light on the issue or perhaps give an update on the issue?

**Comment by 0xElessar** [comment]
Similar, I used the docker image:

[!] Connecting...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/cmd2/cmd2.py", line 1716, in onecmd_plus_hooks
    stop = self.onecmd(statement)
  File "/usr/local/lib/python3.6/site-packages/cmd2/cmd2.py", line 1951, in onecmd
    stop = func(statement)
  File "/usr/local/lib/python3.6/site-packages/cmd2/cmd2.py", line 241, in cmd_wrapper
    return func(instance, args)
  File "/mqtt_pwn/mqtt_pwn/shell/mixins/connect.py", line 40, in do_connect
    self._connect(args)
  File "/mqtt_pwn/mqtt_pwn/shell/mixins/connect.py", line 82, in _connect
    self.mqtt_client.run()
AttributeError: 'NoneType' object has no attribute 'run'
EXCEPTION of type 'AttributeError' occurred with message: ''NoneType' object has no attribute 'run''

**Comment by Den1al** [comment]
Thank you all for letting us know. We had an issue with a buggy PR, now we resolved it.
