### ISSUE TITLE
Update 'idna-ssl'

### ISSUE THREAD

**Issue by whoot** [akamai-threat-research/mqtt-pwn#7]
The used idna-ssl version referenced in requirements.txt is outdated:
```
Could not find a version that satisfies the requirement idna-ssl==1.0.1 (from -r requirements.txt (line 16)) (from versions: 0.0.1, 0.0.2, 1.0.0, 1.1.0)
No matching distribution found for idna-ssl==1.0.1 (from -r requirements.txt (line 16))
```

Please use a newer version e.g. ```idna-ssl==1.1.0```

**Comment by OpM3TA** [comment]
Still an issue???

**Comment by whoot** [comment]
Kind of.
When using the requirements.txt in #10 I get a different issue though:

```
Collecting peewee==3.3.2 (from -r requirements.txt (line 23))
  Using cached peewee-3.3.2.tar.gz (592 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      <string>:22: UserWarning: Cython C extensions for peewee will NOT be built, because Cython does not seem to be installed. To enable Cython C extensions, install Cython >=0.22.1.
      /tmp/pip-install-azpyi26t/peewee_98f8273d7d254562a30f3a7aed434a71/peewee.py:2332: SyntaxWarning: invalid escape sequence '\w'
        index_name = re.sub('[^\w]+', '',
      /tmp/pip-install-azpyi26t/peewee_98f8273d7d254562a30f3a7aed434a71/peewee.py:4760: SyntaxWarning: invalid escape sequence '\w'
        else re.sub('[^\w]+', '_', self.name))
      Traceback (most recent call last):
        File "/home/kali/mqtt-pwn/smart/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
          main()
          ~~~~^^
        File "/home/kali/mqtt-pwn/smart/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
          json_out["return_val"] = hook(**hook_input["kwargs"])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/kali/mqtt-pwn/smart/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 143, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-wj32lp9g/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 331, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-wj32lp9g/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 301, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-wj32lp9g/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 512, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-wj32lp9g/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 317, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 72, in <module>
        File "/tmp/pip-install-azpyi26t/peewee_98f8273d7d254562a30f3a7aed434a71/peewee.py", line 163, in <module>
          from collections import Callable
      ImportError: cannot import name 'Callable' from 'collections' (/usr/lib/python3.13/collections/__init__.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Cython is installed, though. This problem can be resolved by changing `peewee==3.3.2`to `peewee`(which installs 3.18.1).

However, running mqtt-pwn does not work, as I get the following error message:

```
╰─❯ python3 run.py                                                                                                                                                                        ─╯
Traceback (most recent call last):
  File "/home/kali/mqtt-pwn/run.py", line 1, in <module>
    from mqtt_pwn import cli, db
  File "/home/kali/mqtt-pwn/mqtt_pwn/__init__.py", line 1, in <module>
    from mqtt_pwn.connection.mqtt_client import MqttClient
  File "/home/kali/mqtt-pwn/mqtt_pwn/connection/mqtt_client.py", line 3, in <module>
    from mqtt_pwn import utils
  File "/home/kali/mqtt-pwn/mqtt_pwn/utils/__init__.py", line 4, in <module>
    from blessings import Terminal
  File "/home/kali/mqtt-pwn/smart/lib/python3.13/site-packages/blessings/__init__.py", line 29, in <module>
    raise ImportError('Blessings needs Python 3.2.3 or greater for Python 3 '
                      'support due to http://bugs.python.org/issue10570.')
ImportError: Blessings needs Python 3.2.3 or greater for Python 3 support due to http://bugs.python.org/issue10570.
```

But I have version 3.13.3 installed:
```
❯ python3 -V                                                                                                                                                                            
Python 3.13.3
```

**Comment by OpM3TA** [comment]
> Kind of. When using the requirements.txt in [#10](https://github.com/akamai-threat-research/mqtt-pwn/pull/10) I get a different issue though:
> 
> ```
> Collecting peewee==3.3.2 (from -r requirements.txt (line 23))
>   Using cached peewee-3.3.2.tar.gz (592 kB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... error
>   error: subprocess-exited-with-error
>   
>   × Getting requirements to build wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [30 lines of output]
>       <string>:22: UserWarning: Cython C extensions for peewee will NOT be built, because Cython does not seem to be installed. To enable Cython C extensions, install Cython >=0.22.1.
>       /tmp/pip-install-azpyi26t/peewee_98f8273d7d254562a30f3a7aed434a71/peewee.py:2332: SyntaxWarning: invalid escape sequence '\w'
>         index_name = re.sub('[^\w]+', '',
>       /tmp/pip-install-azpyi26t/peewee_98f8273d7d254562a30f3a7aed434a71/peewee.py:4760: SyntaxWarning: invalid escape sequence '\w'
>         else re.sub('[^\w]+', '_', self.name))
>       Traceback (most recent call last):
>         File "/home/kali/mqtt-pwn/smart/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
>           main()
>           ~~~~^^
>         File "/home/kali/mqtt-pwn/smart/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
>           json_out["return_val"] = hook(**hook_input["kwargs"])
>                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/home/kali/mqtt-pwn/smart/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 143, in get_requires_for_build_wheel
>           return hook(config_settings)
>         File "/tmp/pip-build-env-wj32lp9g/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 331, in get_requires_for_build_wheel
>           return self._get_build_requires(config_settings, requirements=[])
>                  ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/tmp/pip-build-env-wj32lp9g/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 301, in _get_build_requires
>           self.run_setup()
>           ~~~~~~~~~~~~~~^^
>         File "/tmp/pip-build-env-wj32lp9g/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 512, in run_setup
>           super().run_setup(setup_script=setup_script)
>           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/tmp/pip-build-env-wj32lp9g/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 317, in run_setup
>           exec(code, locals())
>           ~~~~^^^^^^^^^^^^^^^^
>         File "<string>", line 72, in <module>
>         File "/tmp/pip-install-azpyi26t/peewee_98f8273d7d254562a30f3a7aed434a71/peewee.py", line 163, in <module>
>           from collections import Callable
>       ImportError: cannot import name 'Callable' from 'collections' (/usr/lib/python3.13/collections/__init__.py)
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.
> ```
> 
> Cython is installed, though. This problem can be resolved by changing `peewee==3.3.2`to `peewee`(which installs 3.18.1).
> 
> However, running mqtt-pwn does not work, as I get the following error message:
> 
> ```
> ╰─❯ python3 run.py                                                                                                                                                                        ─╯
> Traceback (most recent call last):
>   File "/home/kali/mqtt-pwn/run.py", line 1, in <module>
>     from mqtt_pwn import cli, db
>   File "/home/kali/mqtt-pwn/mqtt_pwn/__init__.py", line 1, in <module>
>     from mqtt_pwn.connection.mqtt_client import MqttClient
>   File "/home/kali/mqtt-pwn/mqtt_pwn/connection/mqtt_client.py", line 3, in <module>
>     from mqtt_pwn import utils
>   File "/home/kali/mqtt-pwn/mqtt_pwn/utils/__init__.py", line 4, in <module>
>     from blessings import Terminal
>   File "/home/kali/mqtt-pwn/smart/lib/python3.13/site-packages/blessings/__init__.py", line 29, in <module>
>     raise ImportError('Blessings needs Python 3.2.3 or greater for Python 3 '
>                       'support due to http://bugs.python.org/issue10570.')
> ImportError: Blessings needs Python 3.2.3 or greater for Python 3 support due to http://bugs.python.org/issue10570.
> ```
> 
> But I have version 3.13.3 installed:
> 
> ```
> ❯ python3 -V                                                                                                                                                                            
> Python 3.13.3
> ```

Python 3.13 is less than version 3.2.
